### Get /api/notes
GET http://localhost:3001/api/notes

### Get /api/notes/:id
GET http://localhost:3001/api/notes/3

### Post /api/notes
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "Note 1",
    "important": true
}

### Delete /api/notes
DELETE  http://localhost:3001/api/notes
content-type: application/json

{
    "id": 4
}

### Put /api/notes
PUT  http://localhost:3001/api/notes
content-type: application/json

{
    "id": 3,
    "content": "Note 3",
    "important": false
}